### ISSUE TITLE
eliminating the QRCode restriction only

### ISSUE THREAD

**Issue by cfry** [Jeija/QRScanJS#3]
This is not a bug report on QRScanJS but I hope its
authors can help me do the opposite of what you have done.
I am using zbar-processor.js and it is ONLY recognizing
QR codes, not EAN-13 or Code 128 barcodes.
Is there some way to turn on/off the recognition of
different kinds of bar codes?
Thanks!

**Comment by Jeija** [comment]
In order to support different kinds of codes, you will have compile ZBar into `decoder.js` / `decoder.min.js` again (with emscripten). Please see what wrote in the [Compilation section](https://github.com/Jeija/QRScanJS#compilation) of the README.

Also look at this comment in the compilation script: https://github.com/Jeija/QRScanJS/blob/master/generate-decoder.sh#L14

See this section of the ZBar code for a list of supported code types: https://github.com/ZBar/ZBar/blob/master/zbar/config.c#L51

Warning: Compiling the code with emscripten might be a little tricky to get working.
